name: GenSprout
version: 1.0.2
main: com.github.gensprout.GenSprout
bootstrapper: com.github.gensprout.GenSproutBootstrap
api-version: '1.21'
description: A customizable farming and optimized generator plugin with Dialog UI.
author: chyaroscuric
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
commands:
  gensprout:
    description: Main command for GenSprout.
    aliases: [gs, sprout]
  sell:
    description: Sell all crop items in your inventory.
    aliases: [sellall]
  genshop:
    description: Open the generator shop directly.
    aliases: [gshop]
  prestige:
    description: Open the Prestige Menu.

permissions:
  gensprout.admin:
    description: Allows players to use admin features of GenSprout.
    default: op